---- MODULE MCLedgerRequiredBlocksAssumed ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
EXTENDS Ledger

Reachable == {
    "BoundaryEqualitySoundness",
    "ExitClosureForC1",
    "FiberDefinitionAdapter",
    "ResidualClosureNoMissingLinks",
    "SeparatorCatalogueCompleteness",
    "SeparatorCatalogueSoundness",
    "TheoremTagAssumptionPayloads",
    "TheoremTagImportLedger",
    "TheoremTagImportSoundness",
    "TheoremTagPayloadInstances"
}
EventuallyReachable == <>(established = Reachable)
====
