---- MODULE MCLedgerImports ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
EXTENDS Ledger

Reachable == {
    "TheoremTagAssumptionPayloads",
    "TheoremTagImportLedger"
}
EventuallyReachable == <>(established = Reachable)
====
