---- MODULE Ledger ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
(* Repository: larsbx/finite-mandlebrot-research. *)
(* Results are named proof records. Requires is one-way dependency, never a *)
(* converse implication. ProvedDef holds the accepted in-repository records, *)
(* ImportedDef the accepted imported theorems, BoundedDef the bounded        *)
(* experiments, WithdrawnDef the withdrawn claims.                           *)
EXTENDS ProofArchitecture

ResultSet == {
    "BoundaryEqualitySoundness",
    "C1",
    "ExitClosureForC1",
    "FiberDefinitionAdapter",
    "ResidualClosureNoMissingLinks",
    "SeparatorCatalogueCompleteness",
    "SeparatorCatalogueSoundness",
    "TheoremTagAssumptionPayloads",
    "TheoremTagImportLedger",
    "TheoremTagImportSoundness",
    "TheoremTagPayloadInstances"
}

RequiresDef == [r \in ResultSet |->
    CASE r = "BoundaryEqualitySoundness" -> {}
      [] r = "C1" -> {"SeparatorCatalogueSoundness", "SeparatorCatalogueCompleteness", "FiberDefinitionAdapter", "ResidualClosureNoMissingLinks", "ExitClosureForC1", "BoundaryEqualitySoundness", "TheoremTagImportSoundness", "TheoremTagPayloadInstances"}
      [] r = "ExitClosureForC1" -> {}
      [] r = "FiberDefinitionAdapter" -> {}
      [] r = "ResidualClosureNoMissingLinks" -> {}
      [] r = "SeparatorCatalogueCompleteness" -> {}
      [] r = "SeparatorCatalogueSoundness" -> {}
      [] r = "TheoremTagAssumptionPayloads" -> {}
      [] r = "TheoremTagImportLedger" -> {}
      [] r = "TheoremTagImportSoundness" -> {}
      [] r = "TheoremTagPayloadInstances" -> {}]

ProvedDef == {
    "TheoremTagAssumptionPayloads",
    "TheoremTagImportLedger"
}

ImportedDef == {}

BoundedDef == {}

WithdrawnDef == {}

NoAssumptions == {}
ImportsAssumed == ImportedDef
RequiredBlocksAssumed == {
    "SeparatorCatalogueSoundness",
    "SeparatorCatalogueCompleteness",
    "FiberDefinitionAdapter",
    "ResidualClosureNoMissingLinks",
    "ExitClosureForC1",
    "BoundaryEqualitySoundness",
    "TheoremTagImportSoundness",
    "TheoremTagPayloadInstances"
}

(* Observables: one per result, asserting that it is not established. A model *)
(* lists those its assumptions leave unreachable; TLC then checks the closure.  *)
BoundaryEqualitySoundnessNotEstablished == "BoundaryEqualitySoundness" \notin established
C1NotEstablished == "C1" \notin established
ExitClosureForC1NotEstablished == "ExitClosureForC1" \notin established
FiberDefinitionAdapterNotEstablished == "FiberDefinitionAdapter" \notin established
ResidualClosureNoMissingLinksNotEstablished == "ResidualClosureNoMissingLinks" \notin established
SeparatorCatalogueCompletenessNotEstablished == "SeparatorCatalogueCompleteness" \notin established
SeparatorCatalogueSoundnessNotEstablished == "SeparatorCatalogueSoundness" \notin established
TheoremTagAssumptionPayloadsNotEstablished == "TheoremTagAssumptionPayloads" \notin established
TheoremTagImportLedgerNotEstablished == "TheoremTagImportLedger" \notin established
TheoremTagImportSoundnessNotEstablished == "TheoremTagImportSoundness" \notin established
TheoremTagPayloadInstancesNotEstablished == "TheoremTagPayloadInstances" \notin established

====
